[mongodb]
mongodb-dev.devcops.online

[catalogue]
catalogue-dev.devcops.online

[redis]
redis-dev.devcops.online

[user]
user-dev.devcops.online

[cart]
cart-dev.devcops.online

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321